# ansible-playbook deploy.yaml -i inventories/prod/hosts --vault-id ~/.tokens/master_id

- hosts: tools
  strategy: linear

  tasks:

    - name: 'Ensure existence of configuration directory: {{ directories_files }}/config'
      command: mkdir -p {{ directories_files }}/config
      args:
        warn: no

    - name: Render docker-compose.yaml & deploy stack
      import_role:
        name: docker-deploy
      vars:
        with_registry: no
